export let events = [
    {
      id: 8,
      title: 'CyQuiz',
      date: `8.10.2022`,
      imageUrl: '/assets/events/9.png',
      previewImg: '/assets/events/9_small.webp',
      url: 'https://forms.gle/A1qLzVcnAJxYFCMy6',
      body: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ab, ut?",
      actual: true
    },
    {
      id: 7,
      title: 'KICK-OFF FTC',
      date: `10.09.2022 - 11.09.2022`,
      imageUrl: '/assets/events/8.jpg',
      previewImg: '/assets/events/8_small.webp',
      url: 'https://www.youtube.com/watch?v=MmZAB44qF_I&t=200s',
      actual: false,
    },
    {
      id: 6,
      title: 'House of CyLiis',
      date: `27.08.2022 - 4.09.2022`,
      imageUrl: '/assets/events/7.png',
      previewImg: '/assets/events/7_small.webp',
      url: 'https://docs.google.com/forms/d/e/1FAIpQLSfkJ60Gr3bGOHCKI_l3Yb0GK-4BSRlQKc-6y9Vc7r4YkLn9GQ/viewform',
      actual: false,
    },
    {
      id: 5,
      title: 'Interviuri',
      date: `30.06.2022 - 10.08.2022`,
      imageUrl: '/assets/events/6.jpg',
      previewImg: '/assets/events/6_small.webp',
      url: 'https://docs.google.com/forms/d/1O-1_C8PVf5wT8fQhSuwpIi4HFoGhJTWR0TA5Dg-XMtQ/edit',
      actual: false,
    },
    {
      id: 4,
      title: 'House of Cyliis',
      date: '29.08.2021 - 05.09.2021',
      imageUrl: '/assets/events/1.jpg',
      previewImg: '/assets/events/1_small.webp',
      url: 'https://www.instagram.com/p/CSZCzkuonf8/?utm_source=ig_web_copy_link',
      actual: false,
    },
    {
      id: 3,
      title: 'Treasure Hunt',
      date: '04.12.2021',
      imageUrl: '/assets/events/2.jpg',
      previewImg: '/assets/events/2_small.webp',
      url: 'https://www.instagram.com/p/CWwBDZdoKxW/?utm_source=ig_web_copy_link',
      actual: false,
    },
    {
      id: 2,
      title: 'Cylloween Trick or Print',
      date: '29.10.2021 - 31.10.2021',
      imageUrl: '/assets/events/3.jpg',
      previewImg: '/assets/events/3_small.webp',
      url: 'https://www.instagram.com/p/CVfQ6HLBgsX/?utm_source=ig_web_copy_link',
      actual: false,
    },
    {
      id: 1,
      title: 'CyJam',
      date: '26.02.2022 - 15.03.2022',
      imageUrl: '/assets/events/4.jfif',
      previewImg: '/assets/events/4_small.webp',
      url: 'https://www.instagram.com/p/CacofISII7_/?utm_source=ig_web_copy_link',
      actual: false,
    },
  ]