export let alumni: Array<any> = [
    {
      imageUrl: "/assets/mentors/IulianSavastre.jpg",
      name: 'Iulian Savastre',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
      mentor : true,
    },
    {
      name: 'Tudor Chiril\u0103',
      Instagram: 'https://www.instagram.com/tchirila3/',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
      imageUrl: "/assets/members/Tudor Chirila.jpg",
    },
    {
      imageUrl: "/assets/mentors/AndraSmirnov.jpg",
      name: 'Andra Smirnov',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/AndreiAvram.jpg",
      name: 'Andrei Avram',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/AndreiUdila.jpg",
      name: 'Andrei Udila',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/CatalinPuricoi.jpg",
      name: 'Catalin Puricoi',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DanCroitoriu.jpg",
      name: 'Dan Croitoriu',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DanielaGirleanu.jpg",
      name: 'Daniela Girleanu',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/HoriaTurcuman.jpg",
      name: 'Horia Turcuman',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/IustinianNegrei.jpg",
      name: 'Iustinian Negrei',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/MateiBostan.jpg",
      name: 'Matei Bostan',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/MateiChiriac.jpg",
      name: 'Matei Chiriac',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/MateiChirita.jpg",
      name: 'Matei Chiri\u021b\u0103',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/MihaiMelnic.jpg",
      name: 'Mihai Melnic',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/RaduCostache.jpg",
      name: 'Radu Costache',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/AdiaRomanescu.jpg",
      name: 'Adia Romanescu',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/RaresIordan.jpg",
      name: 'Rares Iordan',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/SabinIlegitim.jpg",
      name: 'Sabin Ilegitim',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/YvonnaFilip.jpg",
      name: 'Yvonna Filip',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DenisBanu.jpg",
      name: 'Denis Banu',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DariaCucos.jpg",
      name: 'Daria Cucos',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/BogdanPlescan.jpg",
      name: 'Bogdan Plescan',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DanielRusu.jpg",
      name: 'Daniel Rusu',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DavidCarausu.jpg",
      name: 'David Carausu',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DragosIgnat.jpg",
      name: 'Dragos Ignat',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/DianaCojocaru.jpg",
      name: 'Diana Cojocaru',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/CodrinSusu.jpg",
      name: 'Codrin Susu',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/AncaIacob.jpg",
      name: 'Anca Iacob',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/RazvanCiopraga.jpg",
      name: 'Razvan Ciopraga',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
    {
      imageUrl: "/assets/mentors/AndreiPreda.jpg",
      name: 'Andrei Preda',
      Instagram: '',
      Facebook: '',
      Github: '',
      Discord: '',
      quote: '',
    },
  ];